#! /usr/bin/env python

import json
import httplib
import sys
import os

if len(sys.argv) < 3:
    print "Usage: ./storify APIKEY PATH"
    exit(1)

api_key = sys.argv[1]
path = sys.argv[2]
page_size = 50

def extract_elements(page=1, elements=[]):
    conn = httplib.HTTPSConnection("api.storify.com")
    conn.request("GET", "/v1/stories/%s?api_key=%s&per_page=%d" % (path, api_key, page_size))
    resp = conn.getresponse()
    contents = json.loads(resp.read())

    # Do req.
    # pull out elements.
    # (page * 50) < total_elements?
      # return extract_elements(page + 1, elements)
      # return elements 

elements = extract_elements()
