#! /usr/bin/env python

import json
import httplib
import sys
import os

if len(sys.argv) < 3:
    print "Usage: ./storify APIKEY PATH >> elements.json"
    exit(1)

api_key = sys.argv[1]
path = sys.argv[2]
page_size = 50
conn = httplib.HTTPSConnection("api.storify.com")

def extract_elements(page=1):
    conn.request("GET", "/v1/stories/%s?api_key=%s&per_page=%d&page=%d" % (path, api_key, page_size, page))
    resp = conn.getresponse()
    contents = json.loads(resp.read())

    total = contents['content']['totalElements']
    elements = contents['content']['elements']

    if (total > (page * page_size)):
        return elements + extract_elements(page + 1)
    else:
        return elements

elements = extract_elements()

print json.dumps(elements)
